/**
 * Created by Administrator on 2016/6/6.
 */
angular.module('starter.controllers',[
    'controllers.tabs',
    'controllers.home',
    'controllers.message',
    'controllers.personal',
    'controllers.shop',
    'controllers.start',
    'controllers.productDetail',
    'controllers.productListByTypeCtrl',
    'controllers.myCenterSetupCtrl',
    'controllers.feedbackCtrl',
    'controllers.walletCtrl',
    'controllers.searchHome',
    'controllers.report',
    'controllers.orderPreview',
    'controllers.orderAddress',
    'controllers.editAddress',
    'controllers.messageTalking',
    'controllers.messageChat',
    'controllers.messageSystemCtrl'])